server:
  port: 10000
spring:
  application:
    name: "consumer"

eureka:
  instance:
    prefer-ip-address: true #使用ip地址进行注册
  client:
    service-url:
      #表明向这台机器注册
      defaultZone: "http://localhost:8761/eureka,http://localhost:8762/eureka,"
    instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
    registry-fetch-interval-seconds: 5