server:
  port: 16001
spring:
  application:
    name: "provider"

eureka:
  instance:
    prefer-ip-address: true #使用ip地址进行注册

  client:
    service-url:
      #表明向这台机器注册
      defaultZone: "http://localhost:8761/eureka,http://localhost:8762/eureka"
    instance:
      lease-expiration-duration-in-seconds: 30 #发现30s没有联系则从注册中心删除
      lease-renewal-interval-in-seconds: 10 #与注册中心每5s通信一次
    registry-fetch-interval-seconds: 5
